<section class="formSection">
	<form id="branchHandlingForm">
		<h2>Branches</h2>
		<div class="inputHolder">
			<label for="branchSelector">
				<div class="labelSpan">Branches</div>
			</label>
			<select class="searchable" name="branchSelector" id ="branchSelector">
				<? foreach ($branches as $branch) : ?>
					<?= '<option value="' . $branch . '" ' . ($activeBranch === $branch ? 'selected' : '') . '>' . $branch . '</option>' ?>
				<? endforeach; ?>
			</select>
			<p class="errorMessage">Error placeholder</p>
		</div>
		<div>
			<button class="main" id="deployBtn">Update</button>
		</div>
		<div id="processScreen">
		</div>
	</form>
</section>