<div class="centered">
	<form id="projectCreateForm">
		<section class="formSection">
			<div class="inputHolder">
				<label for="projectName">
					<div class="labelSpan">Project name</div>
				</label>
				<input
					type="text"
					pattern="<?= $projectNameRegex ?>"
					id="projectName"
					name="projectName"
					placeholder="Name of the project"
				/>
				<p class="errorMessage">Error placeholder</p>
			</div>
			<div class="inputHolder">
				<label for="projectPath">
					<div class="labelSpan">Project path</div>
				</label>
				<input
					type="text"
					pattern="<?= $projectPathRegex ?>"
					id="projectPath"
					name="projectPath"
					placeholder="Path of the project"
				/>
				<p class="errorMessage">Error placeholder</p>
				<p class="infoMessage"></p>
			</div>
			<div>
				<button id="addProjectButton" disabled>Add project</button>
			</div>
			<div class="inputHolder">
				<label for="projectPath">
						<div class="labelSpan">Branches</div>
				</label>
				<select class="searchable" name="branchSelector">
					<? foreach (['dev', 'master', 'main', 'hotfix'] as $branch) : ?>
						<?= '<option value="' . $branch . '" ' . ($activeBranch === $branch ? 'selected' : '') . '>' . $branch . '</option>' ?>
					<? endforeach; ?>
				</select>
			</div>
		</section>
	</form>
</div>