<div class="centered">
	<section class="formSection">
		<form id="branchHandlingForm">
			<h2>Branches</h2>
			<div class="inputHolder">
				<label for="projectPath">
						<div class="labelSpan">Branches</div>
				</label>
				<select class="searchable" name="branchSelector" id ="branchSelector">
					<? foreach ($branches as $branch) : ?>
						<?= '<option value="' . $branch . '" ' . ($activeBranch === $branch ? 'selected' : '') . '>' . $branch . '</option>' ?>
					<? endforeach; ?>
				</select>
				<p class="errorMessage">Error placeholder</p>
			</div>
			<div>
				<button id="deployBtn">Update</button>
			</div>
			<div id="processScreen">
			</div>
		</form>
		<hr />
		<form id="scriptHandlingForm">
			<h2>Build scripts</h2>
		</form>
	</section>
</div>